---
title: "Documentation"
author: "Srotaswati Panda"
date: "08/11/2019"
output: html_document
---

<font size = "3">
Capstone Project for Coursera Data Science with R Specialization
</font>

### Next word prediction using an N-gram model

<font size = "2.5">
#### How to use this app?   
Type in an incomplete phrase in the left panel and adjust the slider for the number of words to predict. Results are displayed in the right panel.

#### How it works?  
The app uses a corpus of words from Swiftkey collected from various blogs, news websites and twitter. It then does some word-processing with regex to separate the data into various ngram lists. Katz backoff with Good-Turing smoothing is used to redistribute the probablities from (n-1)gram model into the ngram model to solve the problem of sparsity. Finally, probablities are calculated for next word for a maximum of last four words. 

Other supporting links for the project are as below:  
1. Milestone report for the project at <https://srotaswati.github.io/Capstone_R/C10.html>  
2. Presentation for the application at <https://srotaswati.github.io/Capstone_R/C10-rpubs.html>  


This project was made towards the fulfilment of course requirements for [John Hopkins Coursera Data Science Specialization](https://www.coursera.org/specialization/jhudatascience/1?utm_medium=listingPage)
</font>